version: '3.8'
services:
  kafka:
    container_name: ecommerce-kafka
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs
  mongodb:
    container_name: ecommerce-filterdb
    image: mongo
    command: mongod --port 27019
    ports:
      - "27019:27019"
    volumes:
      - mongodb_data:/data/db
  inventorydb:
    container_name: ecommerce-inventorydb
    image: mysql
    ports:
      - "3308:3308"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_TCP_PORT=3308
      - VIRTUAL_PORT=3308
    volumes:
      - inventorydb:/data/db
volumes:
  kafka_data:
  mongodb_data:
  inventorydb: